{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data'"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import bitcoin\n",
    "import datetime\n",
    "from ping3 import ping\n",
    "import random\n",
    "import json\n",
    "import re\n",
    "import multiprocess as mp\n",
    "\n",
    "from IPython.core.interactiveshell import InteractiveShell\n",
    "\n",
    "InteractiveShell.ast_node_interactivity = \"all\"\n",
    "\n",
    "%pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'id': '2205',\n",
       "  'name': '人人网',\n",
       "  'logo': 'http://reg007.u.qiniudn.com/app/renren.jpg',\n",
       "  'desc': '人人网，中国领先的实名制SNS社交网络。加入人人网，找到老同学，结识新朋友。',\n",
       "  'category': '社交',\n",
       "  'home': 'http://www.renren.com/'},\n",
       " {'id': '2217',\n",
       "  'name': '途牛旅游网',\n",
       "  'logo': 'http://reg007.u.qiniudn.com/app/tuniu.jpg',\n",
       "  'desc': '途牛旅游网-中国专业全面的旅游网,客户满意度94%;提供自助游(自由行),国内旅游,出境旅游,自驾游,公司旅游。低价保证,专业服务,九大出游保障,服务超百万人出游。',\n",
       "  'category': '旅行',\n",
       "  'home': 'http://www.tuniu.com/'},\n",
       " {'id': '2224',\n",
       "  'name': '酷讯旅游网',\n",
       "  'logo': 'http://reg007.u.qiniudn.com/app/kuxun.jpg',\n",
       "  'desc': '酷讯旅游网(Kuxun.cn)是中国领先的在线旅游媒体。为您提供低价可靠的国内国际机票，特价机票99元起，另提供全国20万家酒店预订查询、酒店评论，最低2折起，以及列车时刻表、50000多旅游景点的旅游攻略信息，为您的度假提供最佳的旅游线路。',\n",
       "  'category': '旅行',\n",
       "  'home': 'http://www.kuxun.cn/'},\n",
       " {'id': '2246',\n",
       "  'name': '金山词霸',\n",
       "  'logo': 'http://reg007.u.qiniudn.com/app/iciba.jpg',\n",
       "  'desc': '爱词霸英语为广大网友提供在线翻译、在线词典、英语口语、英语学习资料、汉语词典，金山词霸下载等服务，致力于为您提供优质权威的在线英语服务，是5000万英语学习者的首选。',\n",
       "  'category': '工具',\n",
       "  'home': 'http://www.iciba.com/'},\n",
       " {'id': '2247',\n",
       "  'name': '一听音乐网',\n",
       "  'logo': 'http://reg007.u.qiniudn.com/app/1ting.jpg',\n",
       "  'desc': '一听音乐网是中国最大的在线音乐网站，提供免费歌曲在线试听、下载。一听音乐网拥有庞大、完整的曲库，歌曲更新迅速，试听流畅，口碑极佳。一听音乐网，每天听一听。',\n",
       "  'category': '娱乐',\n",
       "  'home': 'http://www.1ting.com/'},\n",
       " {'id': '2250',\n",
       "  'name': '优酷',\n",
       "  'logo': 'http://reg007.u.qiniudn.com/app/youku.jpg',\n",
       "  'desc': '优酷-中国第一视频网站,提供视频播放,视频发布,视频搜索 - 视频服务平台,提供视频播放,视频发布,视频搜索,视频分享 - 优酷视频',\n",
       "  'category': '娱乐',\n",
       "  'home': 'http://www.youku.com/'},\n",
       " {'id': '2252',\n",
       "  'name': '中关村在线',\n",
       "  'logo': 'http://reg007.u.qiniudn.com/app/zol.jpg',\n",
       "  'desc': '中国领先的IT信息与商务门户, 包括新闻, 商城, 硬件, 下载, 游戏, 手机, 评测等40个大型频道，每天发布大量各类产品促销信息及文章专题，是IT行业的厂商, 经销商, IT产品, 解决方案的提供场所。',\n",
       "  'category': '资讯',\n",
       "  'home': 'http://www.zol.com.cn/'},\n",
       " {'id': '2254',\n",
       "  'name': '百合网',\n",
       "  'logo': 'http://reg007.u.qiniudn.com/app/baihe.jpg',\n",
       "  'desc': '百合网，以帮助中国人成就爱情、婚姻为己任。基于“心灵匹配”的全新婚介模式让数百万会员交友成功。近千万发布征婚信息的单身会员。其中，30岁以上真诚对待爱情、追求幸福婚姻的用户近百万；硕士、管理经理、国家机关干部等优秀会员超过20%。超准爱情心理测试，突破了网络交友“知人知面不知心”的难题，让用户能够通过百合先进的介绍系统，找到幸福指数更高的伴侣。中国妇联互联网，婚恋服务领域独家战略合作单位。',\n",
       "  'category': '社交',\n",
       "  'home': 'http://www.baihe.com/'},\n",
       " {'id': '2259',\n",
       "  'name': '爱真心',\n",
       "  'logo': 'http://reg007.u.qiniudn.com/app/izhenxin.png',\n",
       "  'desc': '爱真心：世纪佳缘旗下会员制婚恋交友网站，100%注册会员实名认证。爱真心面向中国城市白领人群，帮助用户寻找真诚、有共同追求的另一半。力求为用户打造真诚、纯粹、简单、现代的婚恋交友网站。',\n",
       "  'category': '社交',\n",
       "  'home': 'http://www.izhenxin.com/'},\n",
       " {'id': '2209',\n",
       "  'name': '淘宝网',\n",
       "  'logo': 'http://reg007.u.qiniudn.com/app/taobao.jpg',\n",
       "  'desc': '淘宝网 - 亚洲最大、最安全的网上交易平台，提供各类服饰、美容、家居、数码、话费/点卡充值… 8亿优质特价商品，同时提供担保交易(先收货后付款)、先行赔付、假一赔三、七天无理由退换货、数码免费维修等安全交易保障服务，让你全面安心享受网上购物乐趣！',\n",
       "  'category': '购物 名站',\n",
       "  'home': 'http://www.taobao.com/'}]"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "with open(\"./website.json\", \"r\") as f:\n",
    "    website_list = json.load(f)\n",
    "\n",
    "website_list[:10]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['www.renren.com',\n",
       " 'www.tuniu.com',\n",
       " 'www.kuxun.cn',\n",
       " 'www.iciba.com',\n",
       " 'www.1ting.com',\n",
       " 'www.youku.com',\n",
       " 'www.zol.com.cn',\n",
       " 'www.baihe.com',\n",
       " 'www.izhenxin.com',\n",
       " 'www.taobao.com']"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pattern = re.compile(\"http://(.+?)/\")\n",
    "url_list = [re.findall(pattern, dic[\"home\"])[0] for dic in website_list]\n",
    "\n",
    "url_list[:10]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'www.meituan.com'"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "text/plain": [
       "0.04405498504638672"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "url = random.choice(url_list)\n",
    "delay = ping(url)\n",
    "\n",
    "url\n",
    "delay"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "def gen_addr():\n",
    "    # 生成一个随机的密钥\n",
    "    while True:\n",
    "        # 生成一个用十六进制表示的长 256 位的私钥（str类型）\n",
    "        private_key = bitcoin.random_key()\n",
    "        # 解码为十进制的整形密钥\n",
    "        decoded_private_key = bitcoin.decode_privkey(private_key, \"hex\")\n",
    "        if 0 < decoded_private_key < bitcoin.N:\n",
    "            break\n",
    "    # print(private_key) #密钥（十六进制,长 256 位）\n",
    "\n",
    "    # 计算地址\n",
    "    # 用 WIF 格式编码密钥\n",
    "    wif_encoded_private_key = bitcoin.encode_privkey(decoded_private_key, \"wif\")\n",
    "    # 用 01 标识的压缩密钥\n",
    "    compressed_private_key = private_key + \"01\"\n",
    "    # 生成 WIF的压缩格式\n",
    "    wif_compressed_private_key = bitcoin.encode_privkey(\n",
    "        bitcoin.decode_privkey(compressed_private_key, \"hex\"), \"wif\"\n",
    "    )\n",
    "    # 计算公钥坐标 K = k * G\n",
    "    public_key = bitcoin.fast_multiply(bitcoin.G, decoded_private_key)\n",
    "    # 计算公钥\n",
    "    hex_encoded_public_key = bitcoin.encode_pubkey(public_key, \"hex\")\n",
    "    # 计算压缩公钥\n",
    "    # if public_key[1] % 2 == 0:  # 两种方式均可\n",
    "    if public_key[1] & 1 == 0:\n",
    "        compressed_prefix = \"02\"\n",
    "    else:\n",
    "        compressed_prefix = \"03\"\n",
    "    # 转十六也可用 bitcoin.encode(xxx, 16)\n",
    "    hex_compressed_public_key = compressed_prefix + hex(public_key[0])[2:]\n",
    "    # print(f'压缩公钥（十六进制）{hex_compressed_public_key} '\n",
    "    #      '（02 开头代表 y 是偶数，03 开头代表 y 是奇数）')\n",
    "    # 传入公钥坐标对象/十六进制公钥值，输出同样的地址\n",
    "    address = bitcoin.pubkey_to_address(public_key)\n",
    "    # print(address) #地址（b58check）（1 开头\n",
    "    return address"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>user_id</th>\n",
       "      <th>address</th>\n",
       "      <th>url</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>1LUjEfWLZhrndJBkkqXABxpaQNQskBZGqY</td>\n",
       "      <td>www.elong.com</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>17Bo6VWMnfks9Amz35MKzKsBZqzBdU7P8m</td>\n",
       "      <td>www.youku.com</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>1DVBvtVz8Gj61Sjvea61TP3vD46xx7ApgB</td>\n",
       "      <td>www.tuan800.com</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>1Gc2G3fHt41uFWbmfLSwLuevXx72m36HGB</td>\n",
       "      <td>www.xianguo.com</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>1JKifazQtMr4F4hBQhBF4Pc2M6cPRkXEn7</td>\n",
       "      <td>www.suning.com</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1995</th>\n",
       "      <td>1995</td>\n",
       "      <td>161WhqU8FV7ZL32S7fBRo6kQzTfosg4kHN</td>\n",
       "      <td>www.aibang.com</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1996</th>\n",
       "      <td>1996</td>\n",
       "      <td>16E1hPw1UGy1uF6ASbTwG2doH1j13sLP17</td>\n",
       "      <td>bbs.dedecms.com</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1997</th>\n",
       "      <td>1997</td>\n",
       "      <td>19F59LeELN4d3hrKoHccq42Cf3Wa1qYxHD</td>\n",
       "      <td>www.100.com</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1998</th>\n",
       "      <td>1998</td>\n",
       "      <td>1Fm8iVjo2ioUDDRP7y1tjS6Cug7AmfDe3E</td>\n",
       "      <td>www.weibo.com</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1999</th>\n",
       "      <td>1999</td>\n",
       "      <td>16EJokGC7RV65T576AimXNBHPFSFZeDNuz</td>\n",
       "      <td>www.ci123.com</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2000 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     user_id                             address              url\n",
       "0          0  1LUjEfWLZhrndJBkkqXABxpaQNQskBZGqY    www.elong.com\n",
       "1          1  17Bo6VWMnfks9Amz35MKzKsBZqzBdU7P8m    www.youku.com\n",
       "2          2  1DVBvtVz8Gj61Sjvea61TP3vD46xx7ApgB  www.tuan800.com\n",
       "3          3  1Gc2G3fHt41uFWbmfLSwLuevXx72m36HGB  www.xianguo.com\n",
       "4          4  1JKifazQtMr4F4hBQhBF4Pc2M6cPRkXEn7   www.suning.com\n",
       "...      ...                                 ...              ...\n",
       "1995    1995  161WhqU8FV7ZL32S7fBRo6kQzTfosg4kHN   www.aibang.com\n",
       "1996    1996  16E1hPw1UGy1uF6ASbTwG2doH1j13sLP17  bbs.dedecms.com\n",
       "1997    1997  19F59LeELN4d3hrKoHccq42Cf3Wa1qYxHD      www.100.com\n",
       "1998    1998  1Fm8iVjo2ioUDDRP7y1tjS6Cug7AmfDe3E    www.weibo.com\n",
       "1999    1999  16EJokGC7RV65T576AimXNBHPFSFZeDNuz    www.ci123.com\n",
       "\n",
       "[2000 rows x 3 columns]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_user = pd.DataFrame(columns=[\"user_id\", \"address\", \"url\"])\n",
    "for i in range(2000):\n",
    "    url = random.choice(url_list)\n",
    "    # while not ping(url):\n",
    "    #     url=random.choice(url_list)\n",
    "    df_user.loc[i] = [i, gen_addr(), url]\n",
    "\n",
    "df_user"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_user.to_csv(\"user.csv\", index=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished round 1\n",
      "Process Process-952:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Finished round 2\n",
      "Finished round 3\n",
      "Finished round 4\n",
      "Finished round 5\n",
      "Finished round 6\n",
      "Finished round 7\n",
      "Finished round 8\n",
      "Process Process-4303:\n",
      "Process Process-4285:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Process Process-4193:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Process Process-4158:\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "Process Process-4289:\n",
      "Traceback (most recent call last):\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Process Process-4290:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Finished round 9\n",
      "Finished round 10\n",
      "Finished round 11\n",
      "Finished round 12\n",
      "Finished round 13\n",
      "Process Process-6930:\n",
      "Process Process-6932:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Process Process-6945:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "Traceback (most recent call last):\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Process Process-6940:\n",
      "Process Process-6936:\n",
      "Process Process-6942:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Finished round 14\n",
      "Finished round 15\n",
      "Finished round 16\n",
      "Finished round 17\n",
      "Finished round 18\n",
      "Process Process-9293:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", lProcess Process-9311:\n",
      "ine 831, in _callmethod\n",
      "    self._connect()\n",
      "Process Process-9294:\n",
      "Process Process-9180:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Process Process-9292:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Process Process-9252:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethodProcess Process-9276:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "\n",
      "    self._connect()\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Process Process-9266:\n",
      "Process Process-9403:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribProcess Process-9384:\n",
      "Process Process-9400:\n",
      "Process Process-9264:\n",
      "Process Process-9378:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "Traceback (most recent call last):\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ute 'connection'\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "Traceback (most recent call last):\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "Traceback (most recent call last):\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Process Process-9443:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", lProcess Process-9444:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "ine 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/mProcess Process-9436:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "iniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Process Process-9442:\n",
      "Process Process-9440:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiproTraceback (most recent call last):\n",
      "cessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 827, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/dongzheng/Codes/PythonWorkspace/CSE5005-Project/data/gen_tx.py\", line 34, in gen_tx\n",
      "    tx_list.append([send_ts, recv_ts, latency, label, from_user, to_user, value])\n",
      "  File \"<string>\", line 2, in append\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 831, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/managers.py\", line 818, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 502, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/multiprocessing/connection.py\", line 630, in SocketClient\n",
      "    s.connect(address)\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "Finished round 19\n",
      "Finished round 20\n",
      "9969\n",
      "[[datetime.datetime(2022, 10, 12, 11, 28, 21, 816994), datetime.datetime(2022, 10, 12, 11, 28, 21, 834958), 0.017963528633117676, 0, '1D59QhANFNFCVxXmcJKhUD5VjDoNBSBxGc', '161WhqU8FV7ZL32S7fBRo6kQzTfosg4kHN', 3.9692229546269218], [datetime.datetime(2022, 10, 12, 11, 28, 21, 841826), datetime.datetime(2022, 10, 12, 11, 28, 21, 888259), 0.04643347263336181, 0, '1B7RMak7rSPdxSmE3eUe4qEgsbbc86XAzq', '1BAtUeRc2t1935tDjnMhKJ4CTT3ERXjF5y', 8.002439342065061], [datetime.datetime(2022, 10, 12, 11, 28, 21, 971778), datetime.datetime(2022, 10, 12, 11, 28, 22, 9799), 0.03802075386047363, 0, '1JWpHrGXyAA1rcoCxY5NR5426kSq9zCkQW', '1Lii4BaJ7AHdPPxh3UapKuP2yUv85NVExh', 3.8825427071905203], [datetime.datetime(2022, 10, 12, 11, 28, 22, 910), datetime.datetime(2022, 10, 12, 11, 28, 22, 34273), 0.033363056182861325, 0, '1BviriMRsBrdj6Tjvxohq5f27r2caPDgt4', '1Cg3yZPAybyHEdBZWk2YKRuhC1FdNrS5k5', 3.9364970034577915], [datetime.datetime(2022, 10, 12, 11, 28, 21, 911149), datetime.datetime(2022, 10, 12, 11, 28, 21, 980410), 0.06926085948944091, 0, '1PnR481Zz6u3MTdtMJnXH8YziHVcd7JcDJ', '12M23XoTqEK1A2F5UPUydpHBWMY6TrsnZd', 1.681064260911026]]\n",
      "------\n",
      "[[datetime.datetime(2022, 10, 12, 11, 28, 21, 816994), datetime.datetime(2022, 10, 12, 11, 28, 21, 834958), 0.017963528633117676, 0, '1D59QhANFNFCVxXmcJKhUD5VjDoNBSBxGc', '161WhqU8FV7ZL32S7fBRo6kQzTfosg4kHN', 3.9692229546269218], [datetime.datetime(2022, 10, 12, 11, 28, 21, 841826), datetime.datetime(2022, 10, 12, 11, 28, 21, 888259), 0.04643347263336181, 0, '1B7RMak7rSPdxSmE3eUe4qEgsbbc86XAzq', '1BAtUeRc2t1935tDjnMhKJ4CTT3ERXjF5y', 8.002439342065061], [datetime.datetime(2022, 10, 12, 11, 28, 21, 878489), datetime.datetime(2022, 10, 12, 11, 28, 21, 900837), 0.022347688674926758, 0, '1FvWp1BZCWNWbN9P5BwMQBCQRJrCiyEf34', '1CyRSXpmjVSXsWBcAaTyV1sUqB2RbqEGo5', 3.84274647766241], [datetime.datetime(2022, 10, 12, 11, 28, 21, 937969), datetime.datetime(2022, 10, 12, 11, 28, 21, 961715), 0.023745560646057127, 0, '16WoGrb6D65KBjodhBFc2fLYaMnn4aNsGs', '19Y3gSmczyJkFJ7hTbL3sYNxjKfiudAMGx', 5.5726236336052315], [datetime.datetime(2022, 10, 12, 11, 28, 21, 911149), datetime.datetime(2022, 10, 12, 11, 28, 21, 980410), 0.06926085948944091, 1, '1PnR481Zz6u3MTdtMJnXH8YziHVcd7JcDJ', '12M23XoTqEK1A2F5UPUydpHBWMY6TrsnZd', 1.681064260911026]]\n"
     ]
    }
   ],
   "source": [
    "!python gen_tx.py;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>send_timestamp</th>\n",
       "      <th>recv_timestamp</th>\n",
       "      <th>latency</th>\n",
       "      <th>label</th>\n",
       "      <th>from</th>\n",
       "      <th>to</th>\n",
       "      <th>value</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2022-10-12 11:28:21.816994</td>\n",
       "      <td>2022-10-12 11:28:21.834958</td>\n",
       "      <td>0.017964</td>\n",
       "      <td>0</td>\n",
       "      <td>1D59QhANFNFCVxXmcJKhUD5VjDoNBSBxGc</td>\n",
       "      <td>161WhqU8FV7ZL32S7fBRo6kQzTfosg4kHN</td>\n",
       "      <td>3.969223</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2022-10-12 11:28:21.841826</td>\n",
       "      <td>2022-10-12 11:28:21.888259</td>\n",
       "      <td>0.046433</td>\n",
       "      <td>0</td>\n",
       "      <td>1B7RMak7rSPdxSmE3eUe4qEgsbbc86XAzq</td>\n",
       "      <td>1BAtUeRc2t1935tDjnMhKJ4CTT3ERXjF5y</td>\n",
       "      <td>8.002439</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2022-10-12 11:28:21.878489</td>\n",
       "      <td>2022-10-12 11:28:21.900837</td>\n",
       "      <td>0.022348</td>\n",
       "      <td>0</td>\n",
       "      <td>1FvWp1BZCWNWbN9P5BwMQBCQRJrCiyEf34</td>\n",
       "      <td>1CyRSXpmjVSXsWBcAaTyV1sUqB2RbqEGo5</td>\n",
       "      <td>3.842746</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2022-10-12 11:28:21.937969</td>\n",
       "      <td>2022-10-12 11:28:21.961715</td>\n",
       "      <td>0.023746</td>\n",
       "      <td>0</td>\n",
       "      <td>16WoGrb6D65KBjodhBFc2fLYaMnn4aNsGs</td>\n",
       "      <td>19Y3gSmczyJkFJ7hTbL3sYNxjKfiudAMGx</td>\n",
       "      <td>5.572624</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2022-10-12 11:28:21.911149</td>\n",
       "      <td>2022-10-12 11:28:21.980410</td>\n",
       "      <td>0.069261</td>\n",
       "      <td>1</td>\n",
       "      <td>1PnR481Zz6u3MTdtMJnXH8YziHVcd7JcDJ</td>\n",
       "      <td>12M23XoTqEK1A2F5UPUydpHBWMY6TrsnZd</td>\n",
       "      <td>1.681064</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9964</th>\n",
       "      <td>2022-10-12 11:37:07.846933</td>\n",
       "      <td>2022-10-12 11:37:07.961303</td>\n",
       "      <td>0.114370</td>\n",
       "      <td>1</td>\n",
       "      <td>1Jw9BHSzEtzVff7qjxxSnyt8JPqN8ko4C4</td>\n",
       "      <td>1GjJ91SYSmeAyCgvjzmA4UBbaWcjAt7XBj</td>\n",
       "      <td>1.762662</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9965</th>\n",
       "      <td>2022-10-12 11:37:07.965230</td>\n",
       "      <td>2022-10-12 11:37:07.999769</td>\n",
       "      <td>0.034539</td>\n",
       "      <td>0</td>\n",
       "      <td>1Faghv74NTSrAtV9kKCkuZz8vLUDU9NyYP</td>\n",
       "      <td>1M8SmdNzt1gzfD34nB9KHDP7j5YzgP8VbR</td>\n",
       "      <td>7.744528</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9966</th>\n",
       "      <td>2022-10-12 11:37:07.987328</td>\n",
       "      <td>2022-10-12 11:37:08.008256</td>\n",
       "      <td>0.020928</td>\n",
       "      <td>0</td>\n",
       "      <td>1HbSAKyZPuSPdPF44g5esNP7iLqfyDJ1cd</td>\n",
       "      <td>1rNiiQKw5UMbnEpqsXKkU5s9CeWh1qJ2p</td>\n",
       "      <td>4.029260</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9967</th>\n",
       "      <td>2022-10-12 11:37:08.011687</td>\n",
       "      <td>2022-10-12 11:37:08.047103</td>\n",
       "      <td>0.035416</td>\n",
       "      <td>0</td>\n",
       "      <td>12bgNUZ8wKetxSBNLTxFDPt4fj52S5bREu</td>\n",
       "      <td>199GuGHpDyG8xrg49XxjLVLixCmziCdCcD</td>\n",
       "      <td>4.795328</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9968</th>\n",
       "      <td>2022-10-12 11:37:07.956771</td>\n",
       "      <td>2022-10-12 11:37:08.075297</td>\n",
       "      <td>0.118526</td>\n",
       "      <td>1</td>\n",
       "      <td>12eeY6KDNfrtitwVPa4M4KvmVwMc8XeNYD</td>\n",
       "      <td>13bbKxJF2mdJemEwb78E4zmQdkw41ftJZE</td>\n",
       "      <td>2.806390</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>9969 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                 send_timestamp             recv_timestamp   latency label  \\\n",
       "0    2022-10-12 11:28:21.816994 2022-10-12 11:28:21.834958  0.017964     0   \n",
       "1    2022-10-12 11:28:21.841826 2022-10-12 11:28:21.888259  0.046433     0   \n",
       "2    2022-10-12 11:28:21.878489 2022-10-12 11:28:21.900837  0.022348     0   \n",
       "3    2022-10-12 11:28:21.937969 2022-10-12 11:28:21.961715  0.023746     0   \n",
       "4    2022-10-12 11:28:21.911149 2022-10-12 11:28:21.980410  0.069261     1   \n",
       "...                         ...                        ...       ...   ...   \n",
       "9964 2022-10-12 11:37:07.846933 2022-10-12 11:37:07.961303  0.114370     1   \n",
       "9965 2022-10-12 11:37:07.965230 2022-10-12 11:37:07.999769  0.034539     0   \n",
       "9966 2022-10-12 11:37:07.987328 2022-10-12 11:37:08.008256  0.020928     0   \n",
       "9967 2022-10-12 11:37:08.011687 2022-10-12 11:37:08.047103  0.035416     0   \n",
       "9968 2022-10-12 11:37:07.956771 2022-10-12 11:37:08.075297  0.118526     1   \n",
       "\n",
       "                                    from                                  to  \\\n",
       "0     1D59QhANFNFCVxXmcJKhUD5VjDoNBSBxGc  161WhqU8FV7ZL32S7fBRo6kQzTfosg4kHN   \n",
       "1     1B7RMak7rSPdxSmE3eUe4qEgsbbc86XAzq  1BAtUeRc2t1935tDjnMhKJ4CTT3ERXjF5y   \n",
       "2     1FvWp1BZCWNWbN9P5BwMQBCQRJrCiyEf34  1CyRSXpmjVSXsWBcAaTyV1sUqB2RbqEGo5   \n",
       "3     16WoGrb6D65KBjodhBFc2fLYaMnn4aNsGs  19Y3gSmczyJkFJ7hTbL3sYNxjKfiudAMGx   \n",
       "4     1PnR481Zz6u3MTdtMJnXH8YziHVcd7JcDJ  12M23XoTqEK1A2F5UPUydpHBWMY6TrsnZd   \n",
       "...                                  ...                                 ...   \n",
       "9964  1Jw9BHSzEtzVff7qjxxSnyt8JPqN8ko4C4  1GjJ91SYSmeAyCgvjzmA4UBbaWcjAt7XBj   \n",
       "9965  1Faghv74NTSrAtV9kKCkuZz8vLUDU9NyYP  1M8SmdNzt1gzfD34nB9KHDP7j5YzgP8VbR   \n",
       "9966  1HbSAKyZPuSPdPF44g5esNP7iLqfyDJ1cd   1rNiiQKw5UMbnEpqsXKkU5s9CeWh1qJ2p   \n",
       "9967  12bgNUZ8wKetxSBNLTxFDPt4fj52S5bREu  199GuGHpDyG8xrg49XxjLVLixCmziCdCcD   \n",
       "9968  12eeY6KDNfrtitwVPa4M4KvmVwMc8XeNYD  13bbKxJF2mdJemEwb78E4zmQdkw41ftJZE   \n",
       "\n",
       "         value  \n",
       "0     3.969223  \n",
       "1     8.002439  \n",
       "2     3.842746  \n",
       "3     5.572624  \n",
       "4     1.681064  \n",
       "...        ...  \n",
       "9964  1.762662  \n",
       "9965  7.744528  \n",
       "9966  4.029260  \n",
       "9967  4.795328  \n",
       "9968  2.806390  \n",
       "\n",
       "[9969 rows x 7 columns]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_tx = pd.read_pickle(\"./tx_9969.pkl\")\n",
    "\n",
    "df_tx"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1783"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sum(df_tx[\"label\"] == 1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "---\n",
    "\n",
    "Generate training data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>send_timestamp</th>\n",
       "      <th>recv_timestamp</th>\n",
       "      <th>latency</th>\n",
       "      <th>label</th>\n",
       "      <th>from</th>\n",
       "      <th>to</th>\n",
       "      <th>value</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2022-10-12 11:28:21.816994</td>\n",
       "      <td>2022-10-12 11:28:21.834958</td>\n",
       "      <td>0.017964</td>\n",
       "      <td>0</td>\n",
       "      <td>1D59QhANFNFCVxXmcJKhUD5VjDoNBSBxGc</td>\n",
       "      <td>161WhqU8FV7ZL32S7fBRo6kQzTfosg4kHN</td>\n",
       "      <td>3.969223</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2022-10-12 11:28:21.841826</td>\n",
       "      <td>2022-10-12 11:28:21.888259</td>\n",
       "      <td>0.046433</td>\n",
       "      <td>0</td>\n",
       "      <td>1B7RMak7rSPdxSmE3eUe4qEgsbbc86XAzq</td>\n",
       "      <td>1BAtUeRc2t1935tDjnMhKJ4CTT3ERXjF5y</td>\n",
       "      <td>8.002439</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2022-10-12 11:28:21.878489</td>\n",
       "      <td>2022-10-12 11:28:21.900837</td>\n",
       "      <td>0.022348</td>\n",
       "      <td>0</td>\n",
       "      <td>1FvWp1BZCWNWbN9P5BwMQBCQRJrCiyEf34</td>\n",
       "      <td>1CyRSXpmjVSXsWBcAaTyV1sUqB2RbqEGo5</td>\n",
       "      <td>3.842746</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2022-10-12 11:28:21.937969</td>\n",
       "      <td>2022-10-12 11:28:21.961715</td>\n",
       "      <td>0.023746</td>\n",
       "      <td>0</td>\n",
       "      <td>16WoGrb6D65KBjodhBFc2fLYaMnn4aNsGs</td>\n",
       "      <td>19Y3gSmczyJkFJ7hTbL3sYNxjKfiudAMGx</td>\n",
       "      <td>5.572624</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2022-10-12 11:28:21.911149</td>\n",
       "      <td>2022-10-12 11:28:21.980410</td>\n",
       "      <td>0.069261</td>\n",
       "      <td>1</td>\n",
       "      <td>1PnR481Zz6u3MTdtMJnXH8YziHVcd7JcDJ</td>\n",
       "      <td>12M23XoTqEK1A2F5UPUydpHBWMY6TrsnZd</td>\n",
       "      <td>1.681064</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9964</th>\n",
       "      <td>2022-10-12 11:37:07.846933</td>\n",
       "      <td>2022-10-12 11:37:07.961303</td>\n",
       "      <td>0.114370</td>\n",
       "      <td>1</td>\n",
       "      <td>1Jw9BHSzEtzVff7qjxxSnyt8JPqN8ko4C4</td>\n",
       "      <td>1GjJ91SYSmeAyCgvjzmA4UBbaWcjAt7XBj</td>\n",
       "      <td>1.762662</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9965</th>\n",
       "      <td>2022-10-12 11:37:07.965230</td>\n",
       "      <td>2022-10-12 11:37:07.999769</td>\n",
       "      <td>0.034539</td>\n",
       "      <td>0</td>\n",
       "      <td>1Faghv74NTSrAtV9kKCkuZz8vLUDU9NyYP</td>\n",
       "      <td>1M8SmdNzt1gzfD34nB9KHDP7j5YzgP8VbR</td>\n",
       "      <td>7.744528</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9966</th>\n",
       "      <td>2022-10-12 11:37:07.987328</td>\n",
       "      <td>2022-10-12 11:37:08.008256</td>\n",
       "      <td>0.020928</td>\n",
       "      <td>0</td>\n",
       "      <td>1HbSAKyZPuSPdPF44g5esNP7iLqfyDJ1cd</td>\n",
       "      <td>1rNiiQKw5UMbnEpqsXKkU5s9CeWh1qJ2p</td>\n",
       "      <td>4.029260</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9967</th>\n",
       "      <td>2022-10-12 11:37:08.011687</td>\n",
       "      <td>2022-10-12 11:37:08.047103</td>\n",
       "      <td>0.035416</td>\n",
       "      <td>0</td>\n",
       "      <td>12bgNUZ8wKetxSBNLTxFDPt4fj52S5bREu</td>\n",
       "      <td>199GuGHpDyG8xrg49XxjLVLixCmziCdCcD</td>\n",
       "      <td>4.795328</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9968</th>\n",
       "      <td>2022-10-12 11:37:07.956771</td>\n",
       "      <td>2022-10-12 11:37:08.075297</td>\n",
       "      <td>0.118526</td>\n",
       "      <td>1</td>\n",
       "      <td>12eeY6KDNfrtitwVPa4M4KvmVwMc8XeNYD</td>\n",
       "      <td>13bbKxJF2mdJemEwb78E4zmQdkw41ftJZE</td>\n",
       "      <td>2.806390</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>9969 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                 send_timestamp             recv_timestamp   latency label  \\\n",
       "0    2022-10-12 11:28:21.816994 2022-10-12 11:28:21.834958  0.017964     0   \n",
       "1    2022-10-12 11:28:21.841826 2022-10-12 11:28:21.888259  0.046433     0   \n",
       "2    2022-10-12 11:28:21.878489 2022-10-12 11:28:21.900837  0.022348     0   \n",
       "3    2022-10-12 11:28:21.937969 2022-10-12 11:28:21.961715  0.023746     0   \n",
       "4    2022-10-12 11:28:21.911149 2022-10-12 11:28:21.980410  0.069261     1   \n",
       "...                         ...                        ...       ...   ...   \n",
       "9964 2022-10-12 11:37:07.846933 2022-10-12 11:37:07.961303  0.114370     1   \n",
       "9965 2022-10-12 11:37:07.965230 2022-10-12 11:37:07.999769  0.034539     0   \n",
       "9966 2022-10-12 11:37:07.987328 2022-10-12 11:37:08.008256  0.020928     0   \n",
       "9967 2022-10-12 11:37:08.011687 2022-10-12 11:37:08.047103  0.035416     0   \n",
       "9968 2022-10-12 11:37:07.956771 2022-10-12 11:37:08.075297  0.118526     1   \n",
       "\n",
       "                                    from                                  to  \\\n",
       "0     1D59QhANFNFCVxXmcJKhUD5VjDoNBSBxGc  161WhqU8FV7ZL32S7fBRo6kQzTfosg4kHN   \n",
       "1     1B7RMak7rSPdxSmE3eUe4qEgsbbc86XAzq  1BAtUeRc2t1935tDjnMhKJ4CTT3ERXjF5y   \n",
       "2     1FvWp1BZCWNWbN9P5BwMQBCQRJrCiyEf34  1CyRSXpmjVSXsWBcAaTyV1sUqB2RbqEGo5   \n",
       "3     16WoGrb6D65KBjodhBFc2fLYaMnn4aNsGs  19Y3gSmczyJkFJ7hTbL3sYNxjKfiudAMGx   \n",
       "4     1PnR481Zz6u3MTdtMJnXH8YziHVcd7JcDJ  12M23XoTqEK1A2F5UPUydpHBWMY6TrsnZd   \n",
       "...                                  ...                                 ...   \n",
       "9964  1Jw9BHSzEtzVff7qjxxSnyt8JPqN8ko4C4  1GjJ91SYSmeAyCgvjzmA4UBbaWcjAt7XBj   \n",
       "9965  1Faghv74NTSrAtV9kKCkuZz8vLUDU9NyYP  1M8SmdNzt1gzfD34nB9KHDP7j5YzgP8VbR   \n",
       "9966  1HbSAKyZPuSPdPF44g5esNP7iLqfyDJ1cd   1rNiiQKw5UMbnEpqsXKkU5s9CeWh1qJ2p   \n",
       "9967  12bgNUZ8wKetxSBNLTxFDPt4fj52S5bREu  199GuGHpDyG8xrg49XxjLVLixCmziCdCcD   \n",
       "9968  12eeY6KDNfrtitwVPa4M4KvmVwMc8XeNYD  13bbKxJF2mdJemEwb78E4zmQdkw41ftJZE   \n",
       "\n",
       "         value  \n",
       "0     3.969223  \n",
       "1     8.002439  \n",
       "2     3.842746  \n",
       "3     5.572624  \n",
       "4     1.681064  \n",
       "...        ...  \n",
       "9964  1.762662  \n",
       "9965  7.744528  \n",
       "9966  4.029260  \n",
       "9967  4.795328  \n",
       "9968  2.806390  \n",
       "\n",
       "[9969 rows x 7 columns]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_tx = pd.read_pickle(\"./tx_9969.pkl\")\n",
    "\n",
    "df_tx"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['1LUjEfWLZhrndJBkkqXABxpaQNQskBZGqY',\n",
       " '17Bo6VWMnfks9Amz35MKzKsBZqzBdU7P8m',\n",
       " '1DVBvtVz8Gj61Sjvea61TP3vD46xx7ApgB',\n",
       " '1Gc2G3fHt41uFWbmfLSwLuevXx72m36HGB',\n",
       " '1JKifazQtMr4F4hBQhBF4Pc2M6cPRkXEn7']"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_user=pd.read_csv(\"./user.csv\")\n",
    "\n",
    "user_list=df_user[\"address\"].values.tolist()\n",
    "\n",
    "user_list[:5]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "user_list.index(\"17Bo6VWMnfks9Amz35MKzKsBZqzBdU7P8m\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_user_id(row):\n",
    "    from_user_id=user_list.index(row[\"from\"])\n",
    "    to_user_id=user_list.index(row[\"to\"])\n",
    "    \n",
    "    row[\"from_user_id\"]=from_user_id\n",
    "    row[\"to_user_id\"]=to_user_id\n",
    "    \n",
    "    return row"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>send_timestamp</th>\n",
       "      <th>recv_timestamp</th>\n",
       "      <th>latency</th>\n",
       "      <th>label</th>\n",
       "      <th>from</th>\n",
       "      <th>to</th>\n",
       "      <th>value</th>\n",
       "      <th>from_user_id</th>\n",
       "      <th>to_user_id</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2022-10-12 11:28:21.816994</td>\n",
       "      <td>2022-10-12 11:28:21.834958</td>\n",
       "      <td>0.017964</td>\n",
       "      <td>0</td>\n",
       "      <td>1D59QhANFNFCVxXmcJKhUD5VjDoNBSBxGc</td>\n",
       "      <td>161WhqU8FV7ZL32S7fBRo6kQzTfosg4kHN</td>\n",
       "      <td>3.969223</td>\n",
       "      <td>49</td>\n",
       "      <td>1995</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2022-10-12 11:28:21.841826</td>\n",
       "      <td>2022-10-12 11:28:21.888259</td>\n",
       "      <td>0.046433</td>\n",
       "      <td>0</td>\n",
       "      <td>1B7RMak7rSPdxSmE3eUe4qEgsbbc86XAzq</td>\n",
       "      <td>1BAtUeRc2t1935tDjnMhKJ4CTT3ERXjF5y</td>\n",
       "      <td>8.002439</td>\n",
       "      <td>735</td>\n",
       "      <td>976</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2022-10-12 11:28:21.878489</td>\n",
       "      <td>2022-10-12 11:28:21.900837</td>\n",
       "      <td>0.022348</td>\n",
       "      <td>0</td>\n",
       "      <td>1FvWp1BZCWNWbN9P5BwMQBCQRJrCiyEf34</td>\n",
       "      <td>1CyRSXpmjVSXsWBcAaTyV1sUqB2RbqEGo5</td>\n",
       "      <td>3.842746</td>\n",
       "      <td>443</td>\n",
       "      <td>1530</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2022-10-12 11:28:21.937969</td>\n",
       "      <td>2022-10-12 11:28:21.961715</td>\n",
       "      <td>0.023746</td>\n",
       "      <td>0</td>\n",
       "      <td>16WoGrb6D65KBjodhBFc2fLYaMnn4aNsGs</td>\n",
       "      <td>19Y3gSmczyJkFJ7hTbL3sYNxjKfiudAMGx</td>\n",
       "      <td>5.572624</td>\n",
       "      <td>1076</td>\n",
       "      <td>922</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2022-10-12 11:28:21.911149</td>\n",
       "      <td>2022-10-12 11:28:21.980410</td>\n",
       "      <td>0.069261</td>\n",
       "      <td>1</td>\n",
       "      <td>1PnR481Zz6u3MTdtMJnXH8YziHVcd7JcDJ</td>\n",
       "      <td>12M23XoTqEK1A2F5UPUydpHBWMY6TrsnZd</td>\n",
       "      <td>1.681064</td>\n",
       "      <td>10</td>\n",
       "      <td>1389</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9964</th>\n",
       "      <td>2022-10-12 11:37:07.846933</td>\n",
       "      <td>2022-10-12 11:37:07.961303</td>\n",
       "      <td>0.114370</td>\n",
       "      <td>1</td>\n",
       "      <td>1Jw9BHSzEtzVff7qjxxSnyt8JPqN8ko4C4</td>\n",
       "      <td>1GjJ91SYSmeAyCgvjzmA4UBbaWcjAt7XBj</td>\n",
       "      <td>1.762662</td>\n",
       "      <td>1667</td>\n",
       "      <td>708</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9965</th>\n",
       "      <td>2022-10-12 11:37:07.965230</td>\n",
       "      <td>2022-10-12 11:37:07.999769</td>\n",
       "      <td>0.034539</td>\n",
       "      <td>0</td>\n",
       "      <td>1Faghv74NTSrAtV9kKCkuZz8vLUDU9NyYP</td>\n",
       "      <td>1M8SmdNzt1gzfD34nB9KHDP7j5YzgP8VbR</td>\n",
       "      <td>7.744528</td>\n",
       "      <td>1363</td>\n",
       "      <td>774</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9966</th>\n",
       "      <td>2022-10-12 11:37:07.987328</td>\n",
       "      <td>2022-10-12 11:37:08.008256</td>\n",
       "      <td>0.020928</td>\n",
       "      <td>0</td>\n",
       "      <td>1HbSAKyZPuSPdPF44g5esNP7iLqfyDJ1cd</td>\n",
       "      <td>1rNiiQKw5UMbnEpqsXKkU5s9CeWh1qJ2p</td>\n",
       "      <td>4.029260</td>\n",
       "      <td>786</td>\n",
       "      <td>994</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9967</th>\n",
       "      <td>2022-10-12 11:37:08.011687</td>\n",
       "      <td>2022-10-12 11:37:08.047103</td>\n",
       "      <td>0.035416</td>\n",
       "      <td>0</td>\n",
       "      <td>12bgNUZ8wKetxSBNLTxFDPt4fj52S5bREu</td>\n",
       "      <td>199GuGHpDyG8xrg49XxjLVLixCmziCdCcD</td>\n",
       "      <td>4.795328</td>\n",
       "      <td>177</td>\n",
       "      <td>1503</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9968</th>\n",
       "      <td>2022-10-12 11:37:07.956771</td>\n",
       "      <td>2022-10-12 11:37:08.075297</td>\n",
       "      <td>0.118526</td>\n",
       "      <td>1</td>\n",
       "      <td>12eeY6KDNfrtitwVPa4M4KvmVwMc8XeNYD</td>\n",
       "      <td>13bbKxJF2mdJemEwb78E4zmQdkw41ftJZE</td>\n",
       "      <td>2.806390</td>\n",
       "      <td>1187</td>\n",
       "      <td>552</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>9969 rows × 9 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                 send_timestamp             recv_timestamp   latency  label  \\\n",
       "0    2022-10-12 11:28:21.816994 2022-10-12 11:28:21.834958  0.017964      0   \n",
       "1    2022-10-12 11:28:21.841826 2022-10-12 11:28:21.888259  0.046433      0   \n",
       "2    2022-10-12 11:28:21.878489 2022-10-12 11:28:21.900837  0.022348      0   \n",
       "3    2022-10-12 11:28:21.937969 2022-10-12 11:28:21.961715  0.023746      0   \n",
       "4    2022-10-12 11:28:21.911149 2022-10-12 11:28:21.980410  0.069261      1   \n",
       "...                         ...                        ...       ...    ...   \n",
       "9964 2022-10-12 11:37:07.846933 2022-10-12 11:37:07.961303  0.114370      1   \n",
       "9965 2022-10-12 11:37:07.965230 2022-10-12 11:37:07.999769  0.034539      0   \n",
       "9966 2022-10-12 11:37:07.987328 2022-10-12 11:37:08.008256  0.020928      0   \n",
       "9967 2022-10-12 11:37:08.011687 2022-10-12 11:37:08.047103  0.035416      0   \n",
       "9968 2022-10-12 11:37:07.956771 2022-10-12 11:37:08.075297  0.118526      1   \n",
       "\n",
       "                                    from                                  to  \\\n",
       "0     1D59QhANFNFCVxXmcJKhUD5VjDoNBSBxGc  161WhqU8FV7ZL32S7fBRo6kQzTfosg4kHN   \n",
       "1     1B7RMak7rSPdxSmE3eUe4qEgsbbc86XAzq  1BAtUeRc2t1935tDjnMhKJ4CTT3ERXjF5y   \n",
       "2     1FvWp1BZCWNWbN9P5BwMQBCQRJrCiyEf34  1CyRSXpmjVSXsWBcAaTyV1sUqB2RbqEGo5   \n",
       "3     16WoGrb6D65KBjodhBFc2fLYaMnn4aNsGs  19Y3gSmczyJkFJ7hTbL3sYNxjKfiudAMGx   \n",
       "4     1PnR481Zz6u3MTdtMJnXH8YziHVcd7JcDJ  12M23XoTqEK1A2F5UPUydpHBWMY6TrsnZd   \n",
       "...                                  ...                                 ...   \n",
       "9964  1Jw9BHSzEtzVff7qjxxSnyt8JPqN8ko4C4  1GjJ91SYSmeAyCgvjzmA4UBbaWcjAt7XBj   \n",
       "9965  1Faghv74NTSrAtV9kKCkuZz8vLUDU9NyYP  1M8SmdNzt1gzfD34nB9KHDP7j5YzgP8VbR   \n",
       "9966  1HbSAKyZPuSPdPF44g5esNP7iLqfyDJ1cd   1rNiiQKw5UMbnEpqsXKkU5s9CeWh1qJ2p   \n",
       "9967  12bgNUZ8wKetxSBNLTxFDPt4fj52S5bREu  199GuGHpDyG8xrg49XxjLVLixCmziCdCcD   \n",
       "9968  12eeY6KDNfrtitwVPa4M4KvmVwMc8XeNYD  13bbKxJF2mdJemEwb78E4zmQdkw41ftJZE   \n",
       "\n",
       "         value  from_user_id  to_user_id  \n",
       "0     3.969223            49        1995  \n",
       "1     8.002439           735         976  \n",
       "2     3.842746           443        1530  \n",
       "3     5.572624          1076         922  \n",
       "4     1.681064            10        1389  \n",
       "...        ...           ...         ...  \n",
       "9964  1.762662          1667         708  \n",
       "9965  7.744528          1363         774  \n",
       "9966  4.029260           786         994  \n",
       "9967  4.795328           177        1503  \n",
       "9968  2.806390          1187         552  \n",
       "\n",
       "[9969 rows x 9 columns]"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_data=df_tx.copy()\n",
    "df_data=df_data.apply(get_user_id, axis=1)\n",
    "\n",
    "df_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>recv_timestamp</th>\n",
       "      <th>label</th>\n",
       "      <th>value</th>\n",
       "      <th>from_user_id</th>\n",
       "      <th>to_user_id</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2022-10-12 11:28:21.834958</td>\n",
       "      <td>0</td>\n",
       "      <td>3.969223</td>\n",
       "      <td>49</td>\n",
       "      <td>1995</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2022-10-12 11:28:21.888259</td>\n",
       "      <td>0</td>\n",
       "      <td>8.002439</td>\n",
       "      <td>735</td>\n",
       "      <td>976</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2022-10-12 11:28:21.900837</td>\n",
       "      <td>0</td>\n",
       "      <td>3.842746</td>\n",
       "      <td>443</td>\n",
       "      <td>1530</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2022-10-12 11:28:21.961715</td>\n",
       "      <td>0</td>\n",
       "      <td>5.572624</td>\n",
       "      <td>1076</td>\n",
       "      <td>922</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2022-10-12 11:28:21.980410</td>\n",
       "      <td>1</td>\n",
       "      <td>1.681064</td>\n",
       "      <td>10</td>\n",
       "      <td>1389</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9964</th>\n",
       "      <td>2022-10-12 11:37:07.961303</td>\n",
       "      <td>1</td>\n",
       "      <td>1.762662</td>\n",
       "      <td>1667</td>\n",
       "      <td>708</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9965</th>\n",
       "      <td>2022-10-12 11:37:07.999769</td>\n",
       "      <td>0</td>\n",
       "      <td>7.744528</td>\n",
       "      <td>1363</td>\n",
       "      <td>774</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9966</th>\n",
       "      <td>2022-10-12 11:37:08.008256</td>\n",
       "      <td>0</td>\n",
       "      <td>4.029260</td>\n",
       "      <td>786</td>\n",
       "      <td>994</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9967</th>\n",
       "      <td>2022-10-12 11:37:08.047103</td>\n",
       "      <td>0</td>\n",
       "      <td>4.795328</td>\n",
       "      <td>177</td>\n",
       "      <td>1503</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9968</th>\n",
       "      <td>2022-10-12 11:37:08.075297</td>\n",
       "      <td>1</td>\n",
       "      <td>2.806390</td>\n",
       "      <td>1187</td>\n",
       "      <td>552</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>9969 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                 recv_timestamp  label     value  from_user_id  to_user_id\n",
       "0    2022-10-12 11:28:21.834958      0  3.969223            49        1995\n",
       "1    2022-10-12 11:28:21.888259      0  8.002439           735         976\n",
       "2    2022-10-12 11:28:21.900837      0  3.842746           443        1530\n",
       "3    2022-10-12 11:28:21.961715      0  5.572624          1076         922\n",
       "4    2022-10-12 11:28:21.980410      1  1.681064            10        1389\n",
       "...                         ...    ...       ...           ...         ...\n",
       "9964 2022-10-12 11:37:07.961303      1  1.762662          1667         708\n",
       "9965 2022-10-12 11:37:07.999769      0  7.744528          1363         774\n",
       "9966 2022-10-12 11:37:08.008256      0  4.029260           786         994\n",
       "9967 2022-10-12 11:37:08.047103      0  4.795328           177        1503\n",
       "9968 2022-10-12 11:37:08.075297      1  2.806390          1187         552\n",
       "\n",
       "[9969 rows x 5 columns]"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_data.drop(columns=[\"send_timestamp\", \"latency\", \"from\", \"to\"], inplace=True)\n",
    "\n",
    "df_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>recv_timestamp</th>\n",
       "      <th>label</th>\n",
       "      <th>value</th>\n",
       "      <th>from_user_id</th>\n",
       "      <th>to_user_id</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1665574101834958000</td>\n",
       "      <td>0</td>\n",
       "      <td>3.969223</td>\n",
       "      <td>49</td>\n",
       "      <td>1995</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1665574101888259000</td>\n",
       "      <td>0</td>\n",
       "      <td>8.002439</td>\n",
       "      <td>735</td>\n",
       "      <td>976</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1665574101900837000</td>\n",
       "      <td>0</td>\n",
       "      <td>3.842746</td>\n",
       "      <td>443</td>\n",
       "      <td>1530</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1665574101961715000</td>\n",
       "      <td>0</td>\n",
       "      <td>5.572624</td>\n",
       "      <td>1076</td>\n",
       "      <td>922</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1665574101980410000</td>\n",
       "      <td>1</td>\n",
       "      <td>1.681064</td>\n",
       "      <td>10</td>\n",
       "      <td>1389</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9964</th>\n",
       "      <td>1665574627961303000</td>\n",
       "      <td>1</td>\n",
       "      <td>1.762662</td>\n",
       "      <td>1667</td>\n",
       "      <td>708</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9965</th>\n",
       "      <td>1665574627999769000</td>\n",
       "      <td>0</td>\n",
       "      <td>7.744528</td>\n",
       "      <td>1363</td>\n",
       "      <td>774</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9966</th>\n",
       "      <td>1665574628008256000</td>\n",
       "      <td>0</td>\n",
       "      <td>4.029260</td>\n",
       "      <td>786</td>\n",
       "      <td>994</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9967</th>\n",
       "      <td>1665574628047103000</td>\n",
       "      <td>0</td>\n",
       "      <td>4.795328</td>\n",
       "      <td>177</td>\n",
       "      <td>1503</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9968</th>\n",
       "      <td>1665574628075297000</td>\n",
       "      <td>1</td>\n",
       "      <td>2.806390</td>\n",
       "      <td>1187</td>\n",
       "      <td>552</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>9969 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "           recv_timestamp  label     value  from_user_id  to_user_id\n",
       "0     1665574101834958000      0  3.969223            49        1995\n",
       "1     1665574101888259000      0  8.002439           735         976\n",
       "2     1665574101900837000      0  3.842746           443        1530\n",
       "3     1665574101961715000      0  5.572624          1076         922\n",
       "4     1665574101980410000      1  1.681064            10        1389\n",
       "...                   ...    ...       ...           ...         ...\n",
       "9964  1665574627961303000      1  1.762662          1667         708\n",
       "9965  1665574627999769000      0  7.744528          1363         774\n",
       "9966  1665574628008256000      0  4.029260           786         994\n",
       "9967  1665574628047103000      0  4.795328           177        1503\n",
       "9968  1665574628075297000      1  2.806390          1187         552\n",
       "\n",
       "[9969 rows x 5 columns]"
      ]
     },
     "execution_count": 38,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_data[\"recv_timestamp\"]=df_data[\"recv_timestamp\"].apply(lambda x: x.value)\n",
    "\n",
    "df_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_data.to_pickle(f\"./data_{len(df_data)}.pkl\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.8.12 ('py38')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "e340a0a01ab186b377b016c01aa7d5d1230eddf285ffed81230a024c78a4da64"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
